#!/bin/bash
#
# Install vessel and set into the sudoers list.

# Unofficial Bash Strict Mode
set -e
set -u
set -o pipefail
IFS=$'\n\t'

curl -o /usr/local/bin/vessel https://raw.githubusercontent.com/jackmiras/vessel/master/vessel

sudo chmod +x /usr/local/bin/vessel

sudo sh -c "echo \"$USER ALL = (root) NOPASSWD: /usr/local/bin/vessel\" >> /etc/sudoers"
