#!/bin/bash
#
# Get all Pull Requests head branches, perform a 'git checkout' command
# into those head branches and then run all automated tests.

# Unofficial Bash Strict Mode
set -e
set -u
set -o pipefail
IFS=$'\n\t'

# Imports
# source ../add.sh

# Vars

curl -o /usr/local/bin/vessel https://raw.githubusercontent.com/jackmiras/vessel/master/vessel

sudo chmod +x /usr/local/bin/vessel

sudo sh -c "echo \"$USER ALL = (root) NOPASSWD: /usr/local/bin/vessel\" >> /etc/sudoers"
